version: "3.4"
services:
api:
   build: ./ContosoTraders.Ui.Website/
   app id: 461acd57-7b6e-4f3c-9c5e-9b45a8e8a3f8
   app secret: xQK8Q~2VYl0IUZuLGwQABSe13jYkbG_xxxxx
web:
   build: ./ContosoTraders.Api.Products
